### PR TITLE
Add submenus to the navbar + external link to blog

### PR DESCRIPTION
**Pull request by epsy**

### CODE REVIEW

**Comment by grace-law** [comment]
Yann, 

When people click on Sponsors, can it go to the Sponsors Prospectus Page instead of Our-Sponsors  page.  And, can we link the blog post to medium.com/pybay instead?   

Thanks so much!
Grace

**Comment by epsy** [comment]
Done

**Comment by grace-law** [comment]
Blog is still going to the wrong link :-/  please use medium.com/pybay
ᐧ

Grace Law

PyBay Conference Chair and SF Python Organizer

415-323-0388 / grace@pybay.com


Follow us on twitter at @py_bay

Check out the highlights <https://youtu.be/bKMUUiioi5g> from Inaugural PyBay

**Comment by simeonf** [comment]
Merged. Grace maybe this wasn't on staging but source is linking to medium.com/pybay

**Pull request merged**
