### PR TITLE
Countdown timer

### PR DESCRIPTION
**Pull request by superglu**
The following commits were actually intended to be part of the other pull request #98:
2873bd3
fbd7f3a

This adds a countdown timer to the front page set to Jun 17th 2017 at 1159pm.

### CODE REVIEW

**Comment by epsy** [comment]
I added context to the countdown and a call to action button, and rebased the commit so it doesn't include #98's commits.

Unfortunately the video banner becomes too tall and the PyBay logo shifts under the navigation. I've put it in a separate section just below the video:

https://user-images.githubusercontent.com/685865/27011084-30fb234c-4e69-11e7-8393-6cf518ea646a.png

(Ignore the tear in the video)

**Comment by epsy** [comment]
Deployed to staging.

**Comment by simeonf** [comment]
Rebase off master and tests should all pass now.

**Comment by grace-law** [comment]
Can we move the text for the countdown timer back to the video banner so the info is above the fold instead of creating a new section below the fold?   In the mock up I provided, I have shortened the tag line from "Bringing together Python's most forward thinking innovators & developers" to "Bringing together Python's most forward thinking developers" to accommodate this.  Would that have helped?  Or would it help to make the video banner section taller?

**Comment by epsy** [comment]
I tried with the shorter text, I tried shortening the margins but it still breaks the layout.

The video banner has a fixed height and I'm simply not sure what will break if I increase that height.

**Comment by grace-law** [comment]
Have you tried smaller fonts for the Call-for-proposal texts by chance?
ᐧ

Grace Law

PyBay Conference Chair and SF Python Organizer

415-323-0388 / grace@pybay.com


Follow us on twitter at @py_bay

Subscribe for email updates at www.pybay.com

**Comment by epsy** [comment]
It seems to work with smaller fonts indeed, great idea!

screenshot 2017-06-13 at 01 02 40

**Comment by grace-law** [comment]
Great Yann... let's push this to production!
ᐧ

Grace Law

PyBay Conference Chair and SF Python Organizer

415-323-0388 / grace@pybay.com


Follow us on twitter at @py_bay

Check out the highlights <https://youtu.be/bKMUUiioi5g> from Inaugural PyBay

**Pull request merged**
